server:
  port: 8080

spring:
  application:
    name: warehouse-management-system
  
  datasource:
    url: jdbc:mysql://localhost:3306/wms_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.wms: DEBUG
    org.springframework.web: DEBUG

# MES配置 (WMS作为Modbus Master连接MES)
modbus:
  host: 127.0.0.1
  port: 502
  slaveId: 1
  timeout: 10000
  retries: 3
  heartbeat:
    interval: 30000

# 堆垛机配置 (WMS作为Modbus Master连接堆垛机)
stacker:
  ip: 127.0.0.1
  port: 503
  slaveId: 1
  timeout: 10000
  retries: 3
  heartbeat:
    interval: 30000

