server:
  port: ${PORT:8080}

spring:
  application:
    name: warehouse-management-system
  
  # 暂时禁用数据库连接进行测试
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

logging:
  level:
    com.wms: DEBUG
    org.springframework.web: DEBUG

# MES配置 (WMS作为Modbus Master连接MES)
modbus:
  host: ${MES_HOST:127.0.0.1}
  port: ${MES_PORT:502}
  slaveId: ${MES_SLAVE_ID:1}
  timeout: 10000
  retries: 3
  heartbeat:
    interval: 30000

# 堆垛机配置 (WMS作为Modbus Master连接堆垛机)
stacker:
  ip: ${STACKER_IP:127.0.0.1}
  port: ${STACKER_PORT:503}
  slaveId: ${STACKER_SLAVE_ID:1}
  timeout: 10000
  retries: 3
  heartbeat:
    interval: 30000